judger:
    image: judger
    volumes:
        - /home/CSOJ:/var/judger/code
        - /home/test_case:/var/judger/test_case
        - /home/log:/var/judger/code/judge/log
    environment:
        - rpc_token=SicnuOJ
    ports:
        - "0.0.0.0:8085:8080"
